// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHoDlzzs0fQJE47kC_DP5RNl5f2u6TOQ8',
    appId: '1:277975957851:web:71d175cd731a2d6bff5a7e',
    messagingSenderId: '277975957851',
    projectId: 'presencabox',
    authDomain: 'presencabox.firebaseapp.com',
    storageBucket: 'presencabox.firebasestorage.app',
    measurementId: 'G-BNEMJMX8QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4w0alrik6an1Y7Kf7poRyNEaGxcOvTM',
    appId: '1:277975957851:android:4230dca9185c8846ff5a7e',
    messagingSenderId: '277975957851',
    projectId: 'presencabox',
    storageBucket: 'presencabox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3uErUTGM1fbVk_gF2zOsrYQyOwH_TSCc',
    appId: '1:277975957851:ios:4e3a762e65760954ff5a7e',
    messagingSenderId: '277975957851',
    projectId: 'presencabox',
    storageBucket: 'presencabox.firebasestorage.app',
    iosBundleId: 'com.presencabox.presencaBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHoDlzzs0fQJE47kC_DP5RNl5f2u6TOQ8',
    appId: '1:277975957851:web:d12eb58c0258305dff5a7e',
    messagingSenderId: '277975957851',
    projectId: 'presencabox',
    authDomain: 'presencabox.firebaseapp.com',
    storageBucket: 'presencabox.firebasestorage.app',
    measurementId: 'G-3JCH15LBX6',
  );
}
